#!/bin/bash
name="example"
version="1.0"
summary="example package"
description="example package for build test"
license="gplv3"
release="1"
#source=(http://ftp.gnu.org/gnu/bash/bash-5.0.tar.gz)

_setup(){
	mkdir -p $INSTALLDIR/hello/
	echo "setup" > $INSTALLDIR/hello/setup

}

_build(){
	echo "build" > $INSTALLDIR/hello-build
}

_install(){
	echo "install" > $INSTALLDIR/hello-install
}
