#!/bin/bash
name="example"
version="1.0"
summary="example package"
executable="hello"
description="example package for build test"
builddepends=("gcc")
depends=("hello")
license="gplv3"
release="1"
#source=(http://ftp.gnu.org/gnu/bash/bash-5.0.tar.gz)

_setup(){
	mkdir -p ./bin/
	echo "echo hello world" > ./bin/hello

}

_build(){
	chmod +x ./bin/hello
}

_install(){
	mkdir -p $INSTALLDIR/bin/
	install ./bin/hello $INSTALLDIR/bin/hello
}
