#!/bin/bash
name="unibuild"
version="1.0"
summary="Universal builder"
executable="unibuild"
description="The universal build system for posix"
builddepends=("bash")
depends=("curl" "wget" "bash")
license="gplv3"
release="1"
source=(git+https://gitlab.com/sulinos/devel/unibuild)

_setup(){
	export WORKDIR=$WORKDIR/unibuild

}

_build(){
	chmod +x ./install.sh
}

_install(){
	DESTDIR=$INSTALLDIR ./install.sh
}
