#!/bin/bash
export CURDIR=$(pwd)
export BUILDDIR=/tmp/unibuild
export WORKDIR=$BUILDDIR/work
export INSTALLDIR=$BUILDDIR/install
export PKGDIR=$BUILDDIR/package
mkdir -p $WORKDIR $PKGDIR $INSTALLDIR
info "Build Directory=$BUILDDIR"
