#!/bin/bash
export CURDIR=$(pwd)
export BUILDDIR=$(mktemp -d)
export WORKDIR=$BUILDDIR/work
export INSTALLDIR=$BUILDDIR/install
export PKGDIR=$BUILDDIR/package
[ "$TARGET" == "" ] && export TARGET="default"
mkdir -p $WORKDIR $PKGDIR $INSTALLDIR
