#!/bin/bash
if [ "$HOST" == "" ] ; then
	if [ -d /var/lib/dpkg ] ; then
		export HOST=debian
	elif [ -d /var/lib/inary ] ; then
		export HOST=inary
	elif [ -d /var/lib/pacman ] ; then
		export HOST=arch
	else
		export HOST=default
	fi
fi
info "Host=$HOST"
