#!/bin/bash
export CURDIR=$(pwd)
[ "$BUILDDIR" == "" ] &&  export BUILDDIR=$(mktemp -d)
export WORKDIR=$BUILDDIR/work
export INSTALLDIR=$BUILDDIR/install
export DESTDIR=$INSTALLDIR
export PKGDIR=$BUILDDIR/package
mkdir -p $WORKDIR $PKGDIR $INSTALLDIR
info "Build Directory=$BUILDDIR"
export singlesource=true
