#!/bin/bash
declare -r CURDIR="$(pwd)"
[ "$BUILDDIR" == "" ] &&  export BUILDDIR=$(mktemp -d)
export WORKDIR=$BUILDDIR/work
mkdir -p $WORKDIR
info "Build Directory=$BUILDDIR"
export singlesource=true
