#!/bin/bash
export name="unnamed"
export version="1.0"
export release="1"
export homepage="https://example.github.io"
export url="https://gitlab.com/example"
export priority="unknown"
export date="01.01.1970"
if [ -z $maintainer ]; then 
	export maintainer="packager"
fi
if [ -z $email ]; then
	export email="packager@package.org"
fi
export summary="summary missing"
export description="description missing"
export size="31"
export license="gplv3"
