#!/bin/bash
if [ "$singlesource" == "true" ] ; then

	if [ "$(ls -F $WORKDIR | grep \/$ | wc -l)" == "1" ] ; then
		export WORKDIR="$WORKDIR/$(ls -F $WORKDIR | grep \/$)"
	fi
	info "Single source detected: new workdir => $WORKDIR"
fi
