#!/bin/bash
if [ "$BuildType" == "meson" ] ; then
	_setup(){
		unibuild-meson build ${CONFIG_OPTIONS[@]}
	}

	_build(){
		ninja -C build
	}

	_install(){
		DESTDIR="$INSTALLDIR" meson install -C build
	}
fi
