#!/bin/bash
msg(){
	echo -e "\033[32;1m$*\033[;0m"
}

warn(){
	echo -e "\033[33;1m$*\033[;0m"
}
err(){
	echo -e "\033[31;1m$*\033[;0m" > /dev/stderr
}
info(){
	echo -e "\033[34;1m$*\033[;0m"
}
fail_message() {
	err "$@"
	exit 1
}
