#!/bin/bash
if fn_exists "_setup" || fn_exists "_build" || fn_exists "_install" ; then
	info "Auto build type detection disabled."
elif [ "$BuildType" != "" ] ; then
	info "Build Type found."
elif [ -f "$WORKDIR/meson.build" ] ; then
	BuildType="meson"
elif [ -f "$WORKDIR/CMakeLists.txt" ] ; then
	BuildType="cmake"
elif [ -f "$WORKDIR/setup.py" ] ; then
	BuildType="python"
elif [ -f "$WORKDIR/configure" ] ; then
	BuildType="autotools"
fi
