#!/bin/bash
remove(){
	if [ -e "$1" ] ; then
		warn "Removing $1"
		rm -rf "$1"
	fi
}
remove_additional(){
	remove $INSTALLDIR/usr/share/man
	remove $INSTALLDIR/usr/share/help
	remove $INSTALLDIR/usr/share/locale
	remove $INSTALLDIR/usr/share/doc
}
remove_devel(){
	remove $INSTALLDIR/usr/include
}
